# generated by datamodel-codegen:
#   filename:  agent-task-context.schema.json

from __future__ import annotations
from enum import StrEnum
from pydantic import BaseModel, ConfigDict, Field
from . import common_schema
from typing import Any


class SourceType(StrEnum):
    briefing = 'briefing'
    story = 'story'
    delivery = 'delivery'
    finding = 'finding'
    contract = 'contract'


class ContextManifestItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source_id: str = Field(..., max_length=120, min_length=1)
    source_type: SourceType
    hash: common_schema.Sha256


class AgentTaskContext(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    contract_version: common_schema.ContractVersion
    task_id: common_schema.Uuid
    run_id: common_schema.Uuid
    role: common_schema.AgentRole
    issued_at: common_schema.Timestamp
    expires_at: common_schema.Timestamp
    scopes: list[common_schema.Scope] = Field(..., min_length=1)
    context_manifest: list[ContextManifestItem]
    input: dict[str, Any]
