# generated by datamodel-codegen:
#   filename:  common.schema.json

from __future__ import annotations
from typing import Any, Literal
from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field, RootModel
from uuid import UUID
from enum import StrEnum


class CommonContractDefinitions(RootModel[Any]):
    root: Any = Field(..., title='Common contract definitions')


class Uuid(RootModel[UUID]):
    root: UUID


class Timestamp(RootModel[AwareDatetime]):
    root: AwareDatetime


class Sha256(RootModel[str]):
    root: str = Field(..., pattern='^sha256:[a-f0-9]{64}$')


class ContractVersion(RootModel[Literal['1.0.0']]):
    root: Literal['1.0.0']


class RunState(StrEnum):
    RECEIVED = 'RECEIVED'
    WORKER_QUEUED = 'WORKER_QUEUED'
    WORKER_RUNNING = 'WORKER_RUNNING'
    COMPLETED = 'COMPLETED'
    FAILED = 'FAILED'
    CANCELED = 'CANCELED'


class TaskState(StrEnum):
    PENDING = 'PENDING'
    RUNNING = 'RUNNING'
    SUCCEEDED = 'SUCCEEDED'
    FAILED = 'FAILED'
    TIMED_OUT = 'TIMED_OUT'
    CANCELED = 'CANCELED'


class AgentRole(StrEnum):
    fake = 'fake'
    po = 'po'
    dev = 'dev'
    qa = 'qa'
    runner = 'runner'


class EventActor(StrEnum):
    system = 'system'
    fake_worker = 'fake_worker'
    po = 'po'
    dev = 'dev'
    qa = 'qa'
    runner = 'runner'


class EventType(StrEnum):
    RUN_CREATED = 'RUN_CREATED'
    BRIEFING_RECEIVED = 'BRIEFING_RECEIVED'
    TASK_QUEUED = 'TASK_QUEUED'
    AGENT_STARTED = 'AGENT_STARTED'
    FAKE_WORKER_COMPLETED = 'FAKE_WORKER_COMPLETED'
    STORY_FROZEN = 'STORY_FROZEN'
    PO_COMPLETED = 'PO_COMPLETED'
    DEV_TASK_PLAN_CREATED = 'DEV_TASK_PLAN_CREATED'
    ADR_RECORDED = 'ADR_RECORDED'
    TOOL_EXECUTED = 'TOOL_EXECUTED'
    CODE_DELIVERED = 'CODE_DELIVERED'
    CODE_REDELIVERED = 'CODE_REDELIVERED'
    TEST_PLAN_CREATED = 'TEST_PLAN_CREATED'
    TEST_EXECUTED = 'TEST_EXECUTED'
    FINDING_RECORDED = 'FINDING_RECORDED'
    STORY_ACCEPTED = 'STORY_ACCEPTED'
    STORY_REJECTED = 'STORY_REJECTED'
    NEEDS_HUMAN = 'NEEDS_HUMAN'
    AGENT_FAILED = 'AGENT_FAILED'
    RUN_COMPLETED = 'RUN_COMPLETED'
    RUN_FAILED = 'RUN_FAILED'
    RUN_CANCELED = 'RUN_CANCELED'


class Scope(StrEnum):
    context_read = 'context:read'
    model_invoke = 'model:invoke'
    output_write = 'output:write'
    heartbeat_write = 'heartbeat:write'
    artifact_write = 'artifact:write'


class Uri(RootModel[AnyUrl]):
    root: AnyUrl


class NonEmptyText(RootModel[str]):
    root: str = Field(..., max_length=4000, min_length=1)


class StoryId(RootModel[str]):
    root: str = Field(..., pattern='^STORY-[0-9]{3,}$')


class CriterionId(RootModel[str]):
    root: str = Field(..., pattern='^AC-[0-9]{3,}$')


class ArtifactRef(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    artifact_id: Uuid
    kind: str = Field(..., max_length=80, min_length=1)
    uri: Uri
    media_type: str = Field(..., max_length=120, min_length=3)
    size_bytes: int = Field(..., ge=0)
    sha256: Sha256


class ArgvItem(RootModel[str]):
    root: str = Field(..., max_length=1000, min_length=1)


class Profile(StrEnum):
    python = 'python'
    node = 'node'
    api = 'api'
    browser = 'browser'
    generic = 'generic'


class Environment(RootModel[str]):
    root: str = Field(..., max_length=2000)


class ExecutionSpec(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    argv: list[ArgvItem] = Field(..., max_length=64, min_length=1)
    cwd: str = Field(..., pattern='^/(workspace|tests)(/.*)?$')
    timeout_seconds: int = Field(..., ge=1, le=1800)
    profile: Profile
    environment: dict[str, Environment] | None = Field(None, max_length=32)
