# generated by datamodel-codegen:
#   filename:  common.schema.json

from __future__ import annotations
from typing import Any, Literal
from pydantic import AnyUrl, AwareDatetime, Field, RootModel
from uuid import UUID
from enum import StrEnum


class CommonContractDefinitions(RootModel[Any]):
    root: Any = Field(..., title='Common contract definitions')


class Uuid(RootModel[UUID]):
    root: UUID


class Timestamp(RootModel[AwareDatetime]):
    root: AwareDatetime


class Sha256(RootModel[str]):
    root: str = Field(..., pattern='^sha256:[a-f0-9]{64}$')


class ContractVersion(RootModel[Literal['1.0.0']]):
    root: Literal['1.0.0']


class RunState(StrEnum):
    RECEIVED = 'RECEIVED'
    WORKER_QUEUED = 'WORKER_QUEUED'
    WORKER_RUNNING = 'WORKER_RUNNING'
    COMPLETED = 'COMPLETED'
    FAILED = 'FAILED'
    CANCELED = 'CANCELED'


class TaskState(StrEnum):
    PENDING = 'PENDING'
    RUNNING = 'RUNNING'
    SUCCEEDED = 'SUCCEEDED'
    FAILED = 'FAILED'
    TIMED_OUT = 'TIMED_OUT'
    CANCELED = 'CANCELED'


class AgentRole(StrEnum):
    fake = 'fake'
    po = 'po'
    dev = 'dev'
    qa = 'qa'
    runner = 'runner'


class EventActor(StrEnum):
    system = 'system'
    fake_worker = 'fake_worker'
    po = 'po'
    dev = 'dev'
    qa = 'qa'
    runner = 'runner'


class EventType(StrEnum):
    RUN_CREATED = 'RUN_CREATED'
    BRIEFING_RECEIVED = 'BRIEFING_RECEIVED'
    TASK_QUEUED = 'TASK_QUEUED'
    AGENT_STARTED = 'AGENT_STARTED'
    FAKE_WORKER_COMPLETED = 'FAKE_WORKER_COMPLETED'
    AGENT_FAILED = 'AGENT_FAILED'
    RUN_COMPLETED = 'RUN_COMPLETED'
    RUN_FAILED = 'RUN_FAILED'
    RUN_CANCELED = 'RUN_CANCELED'


class Scope(StrEnum):
    context_read = 'context:read'
    model_invoke = 'model:invoke'
    output_write = 'output:write'
    heartbeat_write = 'heartbeat:write'
    artifact_write = 'artifact:write'


class Uri(RootModel[AnyUrl]):
    root: AnyUrl
