# generated by datamodel-codegen:
#   filename:  create-run-request.schema.json

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field
from . import common_schema


class CreateRunRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    contract_version: common_schema.ContractVersion
    briefing: str = Field(..., max_length=100000, min_length=20)
    client_reference: str | None = Field(None, max_length=120, min_length=1)
