# generated by datamodel-codegen:
#   filename:  dev-delivery.schema.json

from __future__ import annotations
from enum import StrEnum
from pydantic import BaseModel, ConfigDict, Field
from . import common_schema


class Status(StrEnum):
    PASS = 'PASS'
    FAIL = 'FAIL'
    NOT_RUN = 'NOT_RUN'


class CriterionVerification(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    criterion_id: common_schema.CriterionId
    command: list[str] = Field(..., min_length=1)
    exit_code: int
    status: Status


class Status1(StrEnum):
    READY_FOR_QA = 'READY_FOR_QA'
    FAILED = 'FAILED'
    NEEDS_HUMAN = 'NEEDS_HUMAN'


class DevDelivery(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    contract_version: common_schema.ContractVersion
    run_id: common_schema.Uuid
    story_id: common_schema.StoryId
    story_hash: common_schema.Sha256
    revision: int = Field(..., ge=1)
    base_hash: common_schema.Sha256
    commit_hash: str = Field(..., pattern='^[a-f0-9]{40,64}$')
    manifest_hash: common_schema.Sha256
    criterion_verifications: list[CriterionVerification] = Field(..., min_length=1)
    artifacts: list[common_schema.ArtifactRef]
    status: Status1
