# generated by datamodel-codegen:
#   filename:  event-envelope.schema.json

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field
from typing import Any
from . import common_schema


class Meta(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    model: str | None
    tokens_in: int = Field(..., ge=0)
    tokens_out: int = Field(..., ge=0)
    latency_ms: int = Field(..., ge=0)
    container_id: str | None


class EventEnvelope(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    contract_version: common_schema.ContractVersion
    event_id: common_schema.Uuid
    sequence: int = Field(..., ge=1)
    run_id: common_schema.Uuid
    ts: common_schema.Timestamp
    actor: common_schema.EventActor
    type: common_schema.EventType
    correlation_id: str = Field(..., max_length=120, min_length=1)
    causation_id: common_schema.Uuid | None
    task_id: common_schema.Uuid | None
    payload: dict[str, Any]
    meta: Meta
