# generated by datamodel-codegen:
#   filename:  fake-worker-output.schema.json

from __future__ import annotations
from enum import StrEnum
from pydantic import BaseModel, ConfigDict, Field
from . import common_schema


class Status(StrEnum):
    SUCCEEDED = 'SUCCEEDED'
    FAILED = 'FAILED'


class FakeWorkerOutput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    contract_version: common_schema.ContractVersion
    task_id: common_schema.Uuid
    run_id: common_schema.Uuid
    status: Status
    message: str = Field(..., max_length=2000, min_length=1)
    received_context_hash: common_schema.Sha256
    emitted_at: common_schema.Timestamp
