# generated by datamodel-codegen:
#   filename:  po-dev-handoff.schema.json

from __future__ import annotations
from pydantic import BaseModel, ConfigDict
from . import common_schema, po_output_schema


class PoDevHandoff(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    contract_version: common_schema.ContractVersion
    run_id: common_schema.Uuid
    story: po_output_schema.Story
    backlog_hash: common_schema.Sha256
    story_hash: common_schema.Sha256
    po_instructions_hash: common_schema.Sha256
