# generated by datamodel-codegen:
#   filename:  po-output.schema.json

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, RootModel
from . import common_schema
from enum import StrEnum


class CoverageItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    briefing_item: common_schema.NonEmptyText
    story_ids: list[common_schema.StoryId] = Field(..., min_length=1)


class NeedsHumanItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    question: common_schema.NonEmptyText
    blocking: bool


class TextList(RootModel[list[common_schema.NonEmptyText]]):
    root: list[common_schema.NonEmptyText]


class Criterion(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    criterion_id: common_schema.CriterionId
    order: int = Field(..., ge=1)
    description: common_schema.NonEmptyText
    verification: common_schema.NonEmptyText


class Priority(StrEnum):
    MUST = 'MUST'
    SHOULD = 'SHOULD'
    COULD = 'COULD'
    WONT = 'WONT'


class Story(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    story_id: common_schema.StoryId
    title: str = Field(..., max_length=160, min_length=1)
    narrative: common_schema.NonEmptyText
    priority: Priority
    depends_on: list[common_schema.StoryId]
    acceptance_criteria: list[Criterion] = Field(..., min_length=1)
    ready: bool


class PoOutput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    contract_version: common_schema.ContractVersion
    run_id: common_schema.Uuid
    briefing_hash: common_schema.Sha256
    product_goal: common_schema.NonEmptyText
    stories: list[Story] = Field(..., max_length=50, min_length=1)
    constraints: TextList
    assumptions: TextList
    out_of_scope: TextList
    coverage: list[CoverageItem] = Field(..., min_length=1)
    decisions: TextList
    needs_human: list[NeedsHumanItem] = Field(..., max_length=20)
