# generated by datamodel-codegen:
#   filename:  qa-test-plan.schema.json

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field
from . import common_schema


class Case(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    case_id: str = Field(..., pattern='^CASE-[0-9]{3,}$')
    criterion_id: common_schema.CriterionId
    gate: str = Field(..., pattern='^G[0-9]$')
    command: list[str] = Field(..., min_length=1)
    required: bool


class QaTestPlan(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    contract_version: common_schema.ContractVersion
    run_id: common_schema.Uuid
    story_id: common_schema.StoryId
    story_hash: common_schema.Sha256
    delivery_manifest_hash: common_schema.Sha256
    cases: list[Case] = Field(..., min_length=1)
