# generated by datamodel-codegen:
#   filename:  run-response.schema.json

from __future__ import annotations
from pydantic import BaseModel, ConfigDict
from . import common_schema


class Links(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    self: common_schema.Uri
    events: common_schema.Uri


class RunResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    contract_version: common_schema.ContractVersion
    run_id: common_schema.Uuid
    state: common_schema.RunState
    created_at: common_schema.Timestamp
    updated_at: common_schema.Timestamp
    current_task_id: common_schema.Uuid | None
    links: Links
