import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { describe, expect, it } from 'vitest';
import { App } from './App';
const label='O que você quer construir?';
function submit(){fireEvent.change(screen.getByLabelText(label),{target:{value:'Criar um painel de execução observável'}});fireEvent.click(screen.getByRole('button',{name:/iniciar/i}))}
describe('painel responsivo e auditoria',()=>{
 it('valida e preserva briefing curto',()=>{render(<App/>);const field=screen.getByLabelText(label);fireEvent.change(field,{target:{value:'curto'}});fireEvent.click(screen.getByRole('button',{name:/iniciar/i}));expect(screen.getByRole('alert')).toHaveTextContent('20 caracteres');expect(field).toHaveValue('curto')});
 it('carrega eventos tipados e impede fluxo sem briefing',async()=>{render(<App/>);submit();expect(screen.getByRole('status')).toHaveTextContent('carregando');await waitFor(()=>expect(screen.getByText('Briefing recebido')).toBeInTheDocument())});
 it('expõe sequência, causalidade, IDs e detalhes progressivos',async()=>{render(<App/>);submit();await waitFor(()=>expect(screen.getByText('Briefing recebido')).toBeInTheDocument());expect(screen.getByText('Etapa 2')).toBeInTheDocument();fireEvent.click(screen.getAllByText(/Detalhes t/)[0]);expect(screen.getAllByText(/Correlation ID/).length).toBeGreaterThan(0)});
 it('filtra e limpa auditoria',async()=>{render(<App/>);submit();await waitFor(()=>expect(screen.getByText('Briefing recebido')).toBeInTheDocument());fireEvent.click(screen.getByRole('button',{name:'Sistema'}));expect(screen.getAllByText(/Execu/).length).toBeGreaterThan(0);fireEvent.click(screen.getByRole('button',{name:'Limpar filtros'}));expect(screen.getByText('Briefing recebido')).toBeInTheDocument()});
 it('distingue erro de transporte e permite reconectar',()=>{render(<App/>);fireEvent.click(screen.getByRole('button',{name:/simular erro/i}));expect(screen.getByRole('alert')).toHaveTextContent('Falha de transporte');expect(screen.getByRole('button',{name:/tentar/i})).toBeInTheDocument()});
 it('não renderiza marcadores de encoding corrompido em estados ready e error',async()=>{const {unmount}=render(<App/>);submit();await waitFor(()=>expect(screen.getByText('Briefing recebido')).toBeInTheDocument());expect(document.body.textContent).not.toMatch(/\u00c3|\u00c2|\ufffd/);unmount();render(<App/>);fireEvent.click(screen.getByRole('button',{name:/simular erro/i}));expect(document.body.textContent).not.toMatch(/\u00c3|\u00c2|\ufffd/)});
 it('anuncia feedback de cópia e mantém causa na camada principal',async()=>{render(<App/>);submit();await waitFor(()=>expect(screen.getByText('Briefing recebido')).toBeInTheDocument());expect(screen.getAllByText(/Causado pela/).length).toBeGreaterThan(0);fireEvent.click(screen.getAllByRole('button',{name:/Run ID: copiar/i})[0]);expect(await screen.findByText(/Run ID copiado/)).toBeInTheDocument()});
});
