import { useMemo, useState } from 'react';
import { mockEvents, mockRun, type MockEvent } from '../mocks/orchestrator';

const actorLabels: Record<string, string> = { system: 'Sistema', po: 'PO', dev: 'Dev', qa: 'QA', runner: 'Runner' };
function formatDate(value: string) { return new Intl.DateTimeFormat('pt-BR', { hour: '2-digit', minute: '2-digit', second: '2-digit' }).format(new Date(value)); }

export function App() {
  const [briefing, setBriefing] = useState(''); const [submitted, setSubmitted] = useState(false);
  const [phase, setPhase] = useState<'idle' | 'loading' | 'ready' | 'error'>('idle'); const [connection, setConnection] = useState<'connected' | 'reconnecting' | 'disconnected'>('connected');
  const [events, setEvents] = useState<MockEvent[]>([]); const [expanded, setExpanded] = useState<string | null>(null); const [fieldError, setFieldError] = useState('');
  const sortedEvents = useMemo(() => [...events].sort((a, b) => a.sequence - b.sequence), [events]);
  function submit(event: React.FormEvent) { event.preventDefault(); setFieldError(''); if (briefing.trim().length < 20) { setFieldError('Descreva o objetivo com pelo menos 20 caracteres.'); return; } if (submitted) return; setSubmitted(true); setPhase('loading'); window.setTimeout(() => { setEvents([...mockEvents]); setPhase('ready'); }, 250); }
  function simulateError() { setSubmitted(true); setPhase('error'); setEvents([]); }
  function retry() { setPhase('loading'); window.setTimeout(() => { setEvents([...mockEvents]); setPhase('ready'); }, 250); }
  return <main className="shell">
    <header className="topbar"><div><p className="eyebrow">CONTROL PLANE</p><h1>Orquestrador</h1></div><span className={`status status-${connection}`} aria-live="polite"><i />{connection === 'connected' ? 'Conectado' : connection === 'reconnecting' ? 'Reconectando…' : 'Desconectado'}</span></header>
    <section className="hero"><p className="eyebrow">FATIA 1 · OBSERVABILIDADE</p><h2>Briefing para execução</h2><p className="muted">Envie uma vez e acompanhe cada decisão do fluxo em tempo real.</p>
      <form onSubmit={submit} noValidate><label htmlFor="briefing">O que você quer construir?</label><textarea id="briefing" value={briefing} onChange={e => setBriefing(e.target.value)} disabled={submitted} aria-describedby={fieldError ? 'briefing-error' : 'briefing-help'} placeholder="Ex.: Criar uma tela de cadastro com validação…" /><p id="briefing-help" className="hint">O briefing é preservado mesmo se houver um erro.</p>{fieldError && <p id="briefing-error" className="error" role="alert">{fieldError}</p>}<button type="submit" disabled={submitted}>{submitted ? 'Execução enviada' : 'Iniciar execução'}<span aria-hidden="true"> →</span></button>{!submitted && <button type="button" className="secondary demo-error" onClick={simulateError}>Simular erro operacional</button>}</form>
    </section>
    {submitted && <><section className="summary card" aria-labelledby="summary-title"><div className="section-heading"><div><p className="eyebrow">EXECUÇÃO ATUAL</p><h2 id="summary-title">Resumo</h2></div><span className="pill">{phase === 'error' ? 'FAILED' : mockRun.state}</span></div>{phase === 'loading' && <p className="notice" role="status">Criando execução e carregando eventos…</p>}{phase === 'error' && <div className="error-panel" role="alert"><p>Não foi possível carregar esta execução.</p><button onClick={retry}>Tentar novamente</button></div>}<div className="metrics"><div><span>Etapa atual</span><strong>{phase === 'error' ? 'Falha de comunicação' : mockRun.current_stage}</strong></div><div><span>Duração</span><strong>2m 08s</strong></div><div><span>Run ID</span><strong className="mono">{mockRun.run_id}</strong></div><div><span>Container ativo</span><strong className="mono">{mockRun.active_container}</strong></div></div></section><section className="timeline card" aria-labelledby="timeline-title"><div className="section-heading"><div><p className="eyebrow">AUDITORIA</p><h2 id="timeline-title">Timeline de eventos</h2></div><div className="actions"><button className="secondary" onClick={() => setEvents([])}>Limpar eventos</button><button className="secondary" onClick={() => setConnection(c => c === 'connected' ? 'reconnecting' : 'connected')}>{connection === 'connected' ? 'Simular reconexão' : 'Reconectar'}</button></div></div>{connection !== 'connected' && <p className="notice" role="status">A conexão será retomada pelo último sequence recebido. Eventos existentes estão preservados.</p>}{phase !== 'loading' && sortedEvents.length === 0 && <p className="empty">Ainda não há eventos para esta execução.</p>}{phase !== 'loading' && sortedEvents.length > 0 && <ol>{sortedEvents.map(event => <li key={event.event_id}><div className="event-marker" /><article><div className="event-head"><span className="actor">{actorLabels[event.actor]}</span><time dateTime={event.ts}>{formatDate(event.ts)}</time><span className="sequence">#{event.sequence}</span></div><h3>{event.type.replaceAll('_', ' ')}</h3><p>{String(event.payload.summary ?? event.payload.stage ?? 'Evento registrado')}</p><button className="payload-toggle" aria-expanded={expanded === event.event_id} onClick={() => setExpanded(expanded === event.event_id ? null : event.event_id)}>{expanded === event.event_id ? 'Ocultar payload' : 'Ver payload'}</button>{expanded === event.event_id && <pre>{JSON.stringify(event.payload, null, 2)}</pre>}</article></li>)}</ol>}</section></>}
  </main>;
}
