import type { EventEnvelope, RunResponse } from '../generated/contracts';
import { CopyButton } from './CopyButton';
const stages: Record<string, string> = { RECEIVED: 'Entendendo sua necessidade', WORKER_QUEUED: 'Organizando o próximo passo', WORKER_RUNNING: 'Criando sua solução', COMPLETED: 'Sua solução está pronta', FAILED: 'Precisamos revisar uma etapa', CANCELED: 'Criação interrompida' };
const duration = (run: RunResponse) => { const ms = Math.max(0, Date.parse(run.updated_at) - Date.parse(run.created_at)); return `${Math.floor(ms / 60000)}m ${String(Math.floor(ms / 1000) % 60).padStart(2, '0')}s`; };
export function RunSummary({ phase, run, events }: { phase: string; run: RunResponse; events: EventEnvelope[] }) {
  const latest = events[events.length - 1]; const transportError = phase === 'error';
  const lastStarted = [...events].reverse().find((event) => event.type === 'AGENT_STARTED');
  const lastFinished = [...events].reverse().find((event) => ['AGENT_FAILED', 'PO_COMPLETED', 'DEV_COMPLETED', 'TEST_PLAN_CREATED', 'RUN_COMPLETED'].includes(event.type));
  const activeRole = lastStarted && (!lastFinished || lastStarted.sequence > lastFinished.sequence) ? String(lastStarted.payload.role ?? lastStarted.actor) : null;
  const roleLabel: Record<string, string> = { po: 'Planejador', dev: 'Construtor', qa: 'Verificador', runner: 'Executor de testes', fake: 'Preparação' };
  return <section className="summary card" aria-labelledby="summary-title"><div className="section-heading"><div><p className="eyebrow">PROGRESSO</p><h2 id="summary-title">{transportError ? 'Não conseguimos atualizar agora' : stages[run.state]}</h2></div><span className="pill">{run.state === 'COMPLETED' ? 'PRONTO' : run.state === 'FAILED' ? 'ATENÇÃO' : 'EM ANDAMENTO'}</span></div>
    {phase === 'loading' && <p className="notice" role="status">Preparando sua solicitação…</p>}{transportError && <div className="error-panel" role="alert"><p>Sua criação continua em segurança. Tente atualizar a tela em instantes.</p></div>}
    <div className="metrics"><div><span>O que está acontecendo</span><strong>{phase === 'loading' ? 'Aguardando início…' : transportError ? 'Aguardando nova atualização' : stages[run.state]}</strong></div><div><span>Trabalhando agora</span><strong className={activeRole ? 'agent-active' : ''}>{activeRole ? roleLabel[activeRole] ?? activeRole : 'Aguardando próxima etapa'}</strong></div><div><span>Tempo decorrido</span><strong>{phase === 'loading' ? '—' : duration(run)}</strong></div><div><span>Atualizado às</span><strong>{phase === 'loading' ? '—' : new Date(run.updated_at).toLocaleTimeString('pt-BR')}</strong></div></div>
    <details className="trace"><summary>Informações técnicas</summary><div className="identifiers"><span>Identificador da criação <strong className="mono long">{run.run_id}</strong><CopyButton value={run.run_id} label="identificador" /></span>{run.current_task_id && <span>Identificador da etapa <strong className="mono long">{run.current_task_id}</strong><CopyButton value={run.current_task_id} label="etapa" /></span>}<span>Último registro <strong>{latest ? `Etapa ${latest.sequence}` : 'Aguardando'}</strong></span></div></details>
  </section>;
}
